options:
  snap-channel:
    default: "reef/stable"
    type: string
    description: |
      The snap-channel option determines the MicroCeph snap that is
      being installed via charm. Change this option to perform an
      upgrade of MicroCeph. See https://charmhub.io/microceph for
      details on the upgrade process.
  default-pool-size:
    default: 3
    type: int
    description: |
      The default replication factor for pools. Note that changing
      this value only sets the default value; it doesn't change
      the replication factor for existing pools.
  enable-rgw:
    default: False
    type: boolean
    description: |
      Setting this parameter to true enables ceph rados gateway
      on all the storage nodes.
